"""initial_v2

Revision ID: 0a7c75ede96b
Revises: 
Create Date: 2026-03-22 10:59:59.280429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a7c75ede96b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_card_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_rate_card_categories_id'), 'rate_card_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('lifetime_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_client_user_email')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index('ix_clients_user_active', 'clients', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('system_default_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['rate_card_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_default_rates_category_id'), 'system_default_rates', ['category_id'], unique=False)
    op.create_index(op.f('ix_system_default_rates_id'), 'system_default_rates', ['id'], unique=False)
    op.create_table('client_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_documents_client_id'), 'client_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_documents_id'), 'client_documents', ['id'], unique=False)
    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_notes_client_id'), 'client_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_notes_id'), 'client_notes', ['id'], unique=False)
    op.create_table('designer_rate_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('vendor_contact', sa.String(length=100), nullable=True),
    sa.Column('vendor_notes', sa.Text(), nullable=True),
    sa.Column('system_default_id', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['rate_card_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_default_id'], ['system_default_rates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designer_rate_cards_category_id'), 'designer_rate_cards', ['category_id'], unique=False)
    op.create_index(op.f('ix_designer_rate_cards_designer_id'), 'designer_rate_cards', ['designer_id'], unique=False)
    op.create_index(op.f('ix_designer_rate_cards_id'), 'designer_rate_cards', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('residential', 'commercial', name='projecttype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('total_area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('discovery', 'site_visit', 'design', 'quotation', 'proposal_sent', 'approved', 'in_progress', 'completed', name='projectstatus'), nullable=False),
    sa.Column('style_preferences', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('family_size', sa.Integer(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('project_rate_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('designer_rate_id', sa.Integer(), nullable=False),
    sa.Column('override_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['designer_rate_id'], ['designer_rate_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_rate_overrides_designer_rate_id'), 'project_rate_overrides', ['designer_rate_id'], unique=False)
    op.create_index(op.f('ix_project_rate_overrides_id'), 'project_rate_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_project_rate_overrides_project_id'), 'project_rate_overrides', ['project_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'approved', 'revised', 'rejected', name='quotationstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    op.create_index(op.f('ix_quotations_project_id'), 'quotations', ['project_id'], unique=False)
    op.create_index(op.f('ix_quotations_public_token'), 'quotations', ['public_token'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.Enum('bedroom', 'kitchen', 'bathroom', 'living', 'dining', 'study', 'balcony', 'pooja', 'utility', 'entrance', 'passage', 'other', name='roomtype'), nullable=False),
    sa.Column('length', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carpet_area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electrical_points', sa.Integer(), nullable=False),
    sa.Column('plumbing_points', sa.Integer(), nullable=False),
    sa.Column('windows_count', sa.Integer(), nullable=False),
    sa.Column('doors_count', sa.Integer(), nullable=False),
    sa.Column('has_false_ceiling', sa.Boolean(), nullable=False),
    sa.Column('has_flooring_work', sa.Boolean(), nullable=False),
    sa.Column('has_painting', sa.Boolean(), nullable=False),
    sa.Column('has_carpentry', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_project_id'), 'rooms', ['project_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'approved', 'rejected', name='proposalstatus'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('design_approach', sa.Text(), nullable=True),
    sa.Column('material_specifications', sa.Text(), nullable=True),
    sa.Column('timeline_phases', sa.Text(), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('payment_schedule', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('public_token', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_index(op.f('ix_proposals_public_token'), 'proposals', ['public_token'], unique=True)
    op.create_table('quotation_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('section_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['rate_card_categories.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_sections_id'), 'quotation_sections', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_sections_quotation_id'), 'quotation_sections', ['quotation_id'], unique=False)
    op.create_table('quotation_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('designer_rate_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate_source', sa.Enum('system_default', 'designer_master', 'project_override', 'manual', name='ratesource'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designer_rate_id'], ['designer_rate_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['quotation_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_line_items_id'), 'quotation_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_line_items_section_id'), 'quotation_line_items', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_line_items_section_id'), table_name='quotation_line_items')
    op.drop_index(op.f('ix_quotation_line_items_id'), table_name='quotation_line_items')
    op.drop_table('quotation_line_items')
    op.drop_index(op.f('ix_quotation_sections_quotation_id'), table_name='quotation_sections')
    op.drop_index(op.f('ix_quotation_sections_id'), table_name='quotation_sections')
    op.drop_table('quotation_sections')
    op.drop_index(op.f('ix_proposals_public_token'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_rooms_project_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_quotations_public_token'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_project_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_project_rate_overrides_project_id'), table_name='project_rate_overrides')
    op.drop_index(op.f('ix_project_rate_overrides_id'), table_name='project_rate_overrides')
    op.drop_index(op.f('ix_project_rate_overrides_designer_rate_id'), table_name='project_rate_overrides')
    op.drop_table('project_rate_overrides')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_designer_rate_cards_id'), table_name='designer_rate_cards')
    op.drop_index(op.f('ix_designer_rate_cards_designer_id'), table_name='designer_rate_cards')
    op.drop_index(op.f('ix_designer_rate_cards_category_id'), table_name='designer_rate_cards')
    op.drop_table('designer_rate_cards')
    op.drop_index(op.f('ix_client_notes_id'), table_name='client_notes')
    op.drop_index(op.f('ix_client_notes_client_id'), table_name='client_notes')
    op.drop_table('client_notes')
    op.drop_index(op.f('ix_client_documents_id'), table_name='client_documents')
    op.drop_index(op.f('ix_client_documents_client_id'), table_name='client_documents')
    op.drop_table('client_documents')
    op.drop_index(op.f('ix_system_default_rates_id'), table_name='system_default_rates')
    op.drop_index(op.f('ix_system_default_rates_category_id'), table_name='system_default_rates')
    op.drop_table('system_default_rates')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index('ix_clients_user_active', table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_card_categories_id'), table_name='rate_card_categories')
    op.drop_table('rate_card_categories')
    # ### end Alembic commands ###
