"""add_labour_management

Revision ID: 3396137adeb3
Revises: 0a7c75ede96b
Create Date: 2026-03-22 23:46:30.505867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3396137adeb3'
down_revision: Union[str, None] = '0a7c75ede96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alt_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.Enum('civil', 'electrical', 'plumbing', 'carpentry', 'painting', 'false_ceiling', 'flooring', 'hvac', 'modular_kitchen', 'furniture', 'supervisor', 'helper', 'other', name='labourspecialization'), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('id_proof_type', sa.String(length=50), nullable=True),
    sa.Column('id_proof_number', sa.String(length=50), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labours_id'), 'labours', ['id'], unique=False)
    op.create_index(op.f('ix_labours_user_id'), 'labours', ['user_id'], unique=False)
    op.create_table('project_labour_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('labour_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'working', 'completed', 'released', name='assignmentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['labour_id'], ['labours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_labour_assignments_id'), 'project_labour_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_project_labour_assignments_labour_id'), 'project_labour_assignments', ['labour_id'], unique=False)
    op.create_index(op.f('ix_project_labour_assignments_project_id'), 'project_labour_assignments', ['project_id'], unique=False)
    op.create_index('ix_project_labour_unique', 'project_labour_assignments', ['project_id', 'labour_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_labour_unique', table_name='project_labour_assignments')
    op.drop_index(op.f('ix_project_labour_assignments_project_id'), table_name='project_labour_assignments')
    op.drop_index(op.f('ix_project_labour_assignments_labour_id'), table_name='project_labour_assignments')
    op.drop_index(op.f('ix_project_labour_assignments_id'), table_name='project_labour_assignments')
    op.drop_table('project_labour_assignments')
    op.drop_index(op.f('ix_labours_user_id'), table_name='labours')
    op.drop_index(op.f('ix_labours_id'), table_name='labours')
    op.drop_table('labours')
    # ### end Alembic commands ###
