"""add_client_special_discount

Revision ID: 4771a2942656
Revises: abb4a3f05a20
Create Date: 2026-03-23 00:42:46.792559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4771a2942656'
down_revision: Union[str, None] = 'abb4a3f05a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('special_discount', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'special_discount')
    # ### end Alembic commands ###
