"""add_daily_work_log

Revision ID: 4955f77fa546
Revises: 72d158743e0d
Create Date: 2026-03-23 21:18:02.532696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4955f77fa546'
down_revision: Union[str, None] = '72d158743e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'partial', 'no_work', 'holiday', 'rain', 'material_delay', 'labour_absent', 'client_hold', name='workstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('work_category', sa.String(length=100), nullable=True),
    sa.Column('workers_present', sa.Integer(), nullable=True),
    sa.Column('hours_worked', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('photos_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_work_logs_id'), 'daily_work_logs', ['id'], unique=False)
    op.create_index(op.f('ix_daily_work_logs_project_id'), 'daily_work_logs', ['project_id'], unique=False)
    op.create_index('ix_worklog_project_date', 'daily_work_logs', ['project_id', 'log_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worklog_project_date', table_name='daily_work_logs')
    op.drop_index(op.f('ix_daily_work_logs_project_id'), table_name='daily_work_logs')
    op.drop_index(op.f('ix_daily_work_logs_id'), table_name='daily_work_logs')
    op.drop_table('daily_work_logs')
    # ### end Alembic commands ###
