"""add_per_item_gst

Revision ID: 72d158743e0d
Revises: 4771a2942656
Create Date: 2026-03-23 19:34:25.613252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d158743e0d'
down_revision: Union[str, None] = '4771a2942656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_line_items', sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='18'))
    op.add_column('quotation_line_items', sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_line_items', 'gst_amount')
    op.drop_column('quotation_line_items', 'gst_rate')
    # ### end Alembic commands ###
