"""add_company_branding

Revision ID: a275f76eb24d
Revises: 3396137adeb3
Create Date: 2026-03-23 00:22:30.885816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a275f76eb24d'
down_revision: Union[str, None] = '3396137adeb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('company_logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_logo_url')
    op.drop_column('users', 'company_address')
    # ### end Alembic commands ###
