"""add_client_code_quotation_code

Revision ID: abb4a3f05a20
Revises: a275f76eb24d
Create Date: 2026-03-23 00:34:30.552244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb4a3f05a20'
down_revision: Union[str, None] = 'a275f76eb24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.add_column('quotations', sa.Column('quotation_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_quotations_quotation_code'), 'quotations', ['quotation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_quotation_code'), table_name='quotations')
    op.drop_column('quotations', 'quotation_code')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_column('clients', 'client_code')
    # ### end Alembic commands ###
